### ISSUE TITLE
[BUG] Clicking delete on a video from similar videos causes a panic and does not delete video

### ISSUE THREAD

**Issue by ddshd** [qarmin/czkawka#1033]
File was of type `MOV`, the permissions are fine because files in similar photos are able to deleted within the same directories.

Ubuntu 20.04. libheic is installed. Using czkawka gui with heic

```
thread 'main' panicked at 'assertion failed: model.get::<bool>(&iter, column_header)', czkawka_gui/src/help_functions.rs:558:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: czkawka_gui::help_functions::check_how_much_elements_is_selected
   4: glib::main_context_futures::<impl glib::auto::main_context::MainContext>::spawn_local_with_priority::{{closure}}
   5: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
   6: glib::main_context_futures::TaskSource::dispatch
   7: g_main_context_dispatch
   8: <unknown>
   9: g_main_context_iteration
  10: g_application_run
  11: <O as gio::application::ApplicationExtManual>::run_with_args
  12: czkawka_gui::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ServusNL** [comment]
+1 experiencing the game problem in a docker deployment.

**Comment by qarmin** [comment]
Yup, this is fixed, new version will be available soon
