### ISSUE TITLE
reproduceable crash when click on sort by folder

### ISSUE THREAD

**Issue by schnedann** [qarmin/czkawka#1185]
reproduceable crash when click on sort by folder
--> search for duplicates (arbitrary path's work)
--> try to sort resultlist
--> crash

Also, please note: this behaviour was also present in older versions. It's not new.

**System**
Archlinux:

```
Name                     : czkawka-gui
Version                  : 6.1.0-0.1
Beschreibung             : Multi functional app to find duplicates, empty folders, similar images etc. (Desktop App)
Architektur              : x86_64
URL                      : https://github.com/qarmin/czkawka
Lizenzen                 : MIT
Gruppen                  : Nichts
Stellt bereit            : Nichts
Hängt ab von             : bzip2  cairo  gdk-pixbuf2  gtk4  hicolor-icon-theme  libheif  pango
Optionale Abhängigkeiten : Nichts
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 16,15 MiB
Packer                   : Unknown Packager
Erstellt am              : 2024-01-03T22:31:57 CET
Installiert am           : 2024-01-03T22:40:57 CET
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Nichts
```

**Comment by wojteo** [comment]
crashes on windows as well

**Comment by rossorp** [comment]
Confirm that I have the same issue in 7.0.0 (linux_czkawka_gui binary). 

Happens for all sort options for me, not just sort by folder. Seems to only occur when one of the folders is set as a reference folder. If there is no reference folder then Sort doesn't seem to do anything (none of the sort options change the display, nor does anything get output to the console). 

Output for sort by folder with one of two folders set as a reference folder and with `RUST_BACKTRACE=full` below:

```
21:20:43.246 [INFO] czkawka_core::common: App version: 7.0.0, release mode, rust 1.76.0 (2024-02-04), os Fedora 40.0.0 [x86_64 64-bit], 4 cpu/threads
21:20:43.571 [INFO] czkawka_gui: Set thread number to 4

21:20:50.440 [INFO] czkawka_core::duplicate: find_duplicates
21:20:53.571 [INFO] czkawka_core::duplicate: find_duplicates: Done in 3.13s

(linux_czkawka_gui:82800): Gtk-CRITICAL **: 21:20:58.032: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.8.0/src/tree_model.rs:49:14:
Failed to get TreeModel value: ValueTypeMismatchError { actual: <invalid>, requested: gboolean }
stack backtrace:
   0:     0x563c45e78e79 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x563c45e78e79 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563c45e78e79 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x563c45e78e79 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x563c45723d10 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x563c45723d10 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x563c45e41652 - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x563c45e7a9ee - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x563c45e7a9ee - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x563c45e7a190 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:272:22
  10:     0x563c45e7b31b - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x563c45e7b31b - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x563c45e7ad40 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x563c45e7ac96 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x563c45e7ac8f - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x563c45659634 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x563c45659ba2 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x563c459c11af - czkawka_gui::connect_things::connect_popovers_sort::popover_sort_general::h7c32cd89b447a0bd
  18:     0x7f1759269254 - <unknown>
  19:     0x7f1759269361 - g_signal_emit_valist
  20:     0x7f1759269423 - g_signal_emit
  21:     0x7f175869277c - <unknown>
  22:     0x7f1759269254 - <unknown>
  23:     0x7f1759269361 - g_signal_emit_valist
  24:     0x7f1759269423 - g_signal_emit
  25:     0x7f1758732c93 - <unknown>
  26:     0x7f175924cc65 - g_cclosure_marshal_VOID__BOXEDv
  27:     0x7f1759269254 - <unknown>
  28:     0x7f1759269361 - g_signal_emit_valist
  29:     0x7f1759269423 - g_signal_emit
  30:     0x7f1758736584 - <unknown>
  31:     0x7f175873771b - <unknown>
  32:     0x7f175873877d - <unknown>
  33:     0x7f175885c649 - <unknown>
  34:     0x7f175885c9b8 - <unknown>
  35:     0x7f175877798a - <unknown>
  36:     0x7f1758778503 - <unknown>
  37:     0x7f175879fd70 - <unknown>
  38:     0x7f17589d34ee - <unknown>
  39:     0x7f1758a5524a - <unknown>
  40:     0x7f1759269254 - <unknown>
  41:     0x7f1759269361 - g_signal_emit_valist
  42:     0x7f1759269423 - g_signal_emit
  43:     0x7f1758af86d5 - <unknown>
  44:     0x7f17589e4886 - <unknown>
  45:     0x7f1759145e8c - <unknown>
  46:     0x7f17591a7c98 - <unknown>
  47:     0x7f1759147383 - g_main_context_iteration
  48:     0x7f17585130fd - g_application_run
  49:     0x563c459dcaa5 - czkawka_gui::main::hc0ae1e8d656307c2
  50:     0x563c45966bd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8149003a0701ac5e
  51:     0x563c459dc3f4 - main
  52:     0x7f175815b088 - __libc_start_call_main
  53:     0x7f175815b14b - __libc_start_main_impl
  54:     0x563c456cc385 - _start
  55:                0x0 - <unknown>
```
