### ISSUE TITLE
.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:

### ISSUE THREAD

**Issue by chchia** [qarmin/czkawka#1378]
**Bug Description**

**Steps to reproduce:**

**Terminal output** (optional):

```
<!--
Add terminal output only if needed - if there are some errors or warnings or you have performance/freeze issues.  
Very helpful in this situation will be logs from czkawka run with RUST_LOG environment variable set e.g. 
`RUST_LOG=debug ./czkawka` or `flatpak run --env=RUST_LOG=debug com.github.qarmin.czkawka` if you use flatpak, which will print more detailed info about executed function.
-->

<details>
<summary>Debug log</summary>

# UNCOMMENT DETAILS AND PUT LOGS HERE
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow
thread '<unnamed>' panicked at /home/chchia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image_hasher-2.0.0/src/alg/mod.rs:217:9:
attempt to add with overflow

</details>
```

**System**

- Czkawka/Krokiet version: 
- OS version: 
- Installation method:

**Comment by qarmin** [comment]
This is fixed in latest image-hasher repo, which will be included in new version.
For now i suggest to avoid median hash

**Comment by qarmin** [comment]
It is fixed in latest version
