### ISSUE TITLE
cargo test --bin czkawka_gui --release fails on 5.0.0

### ISSUE THREAD

**Issue by fabiscafe** [qarmin/czkawka#790]
Hi. While the build itself is fine, a test fails with the 5.0.0 release on the gui part.

```
   Compiling czkawka_gui v5.0.0 (/build/czkawka/src/czkawka/czkawka_gui)
    Finished release [optimized] target(s) in 4.13s
     Running unittests src/main.rs (target/release/deps/czkawka_gui-b6d67ed82ab0a91f)

running 6 tests
test help_functions::test::test_change_dimension_to_krotka ... ok
test help_functions::test::test_file_name_shortener ... ok
test help_functions::test::test_pixbuf_from_dynamic_image ... ok
thread '<unnamed>' panicked at 'Tests failed to initialize gtk: BoolError { message: "Failed to initialize GTK", filename: "/build/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.8/src/rt.rs", function: "gtk4::rt", line: 145 }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.8/src/lib.rs:88:27
stack backtrace:
   0:     0x5654752c965d - std::backtrace_rs::backtrace::libunwind::trace::h2f06c59e048fd6ef
                               at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5654752c965d - std::backtrace_rs::backtrace::trace_unsynchronized::h312b5329d9b90799
                               at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5654752c965d - std::sys_common::backtrace::_print_fmt::hc5df6e0ae92eab3d
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5654752c965d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h507aa611980ef3ae
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5654752ec41c - core::fmt::write::h84a77b5d03a4d9fd
                               at /rustc/1.62.1/library/core/src/fmt/mod.rs:1196:17
   5:     0x5654752c60d1 - std::io::Write::write_fmt::hee6101c2ca4f56a1
                               at /rustc/1.62.1/library/std/src/io/mod.rs:1654:15
   6:     0x5654752cb135 - std::sys_common::backtrace::_print::h9691b5acf5a0c0cc
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5654752cb135 - std::sys_common::backtrace::print::h0a5971ff57f37f1d
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5654752cb135 - std::panicking::default_hook::{{closure}}::he4caf87b461ee958
                               at /rustc/1.62.1/library/std/src/panicking.rs:295:22
   9:     0x5654752cada9 - std::panicking::default_hook::had807c37bcc92c12
                               at /rustc/1.62.1/library/std/src/panicking.rs:314:9
  10:     0x5654752cb708 - std::panicking::rust_panic_with_hook::hfcce4455d4fbb45f
                               at /rustc/1.62.1/library/std/src/panicking.rs:698:17
  11:     0x5654752cb5b7 - std::panicking::begin_panic_handler::{{closure}}::h930a070c36da4819
                               at /rustc/1.62.1/library/std/src/panicking.rs:588:13
  12:     0x5654752c9b14 - std::sys_common::backtrace::__rust_end_short_backtrace::h4dc186497cf8346b
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5654752cb2e9 - rust_begin_unwind
                               at /rustc/1.62.1/library/std/src/panicking.rs:584:5
  14:     0x5654752583a3 - core::panicking::panic_fmt::h7acba03dfd87b5f5
                               at /rustc/1.62.1/library/core/src/panicking.rs:142:14
  15:     0x565475258493 - core::result::unwrap_failed::h10866056d986ec3a
                               at /rustc/1.62.1/library/core/src/result.rs:1785:5
  16:     0x5654752a3ada - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1f3a9e98633402d2
  17:     0x5654752a7fd8 - glib::thread_pool::spawn_func::h1820352bff8a0fb1
  18:     0x7fd60f05b5e3 - <unknown>
  19:     0x7fd60f058405 - <unknown>
  20:     0x7fd60ec8c54d - <unknown>
  21:     0x7fd60ed11874 - clone
  22:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
error: test failed, to rerun pass '-p czkawka_gui --bin czkawka_gui'

Caused by:
  process didn't exit successfully: `/build/czkawka/src/czkawka/target/release/deps/czkawka_gui-b6d67ed82ab0a91f` (signal: 6, SIGABRT: process abort signal)
```

ArchLinux
* gtk4 4.6.6
* rustup 1.25.1

**Comment by qarmin** [comment]
I completely forgot about adding tests to CI(I was almost sure that they already exists there)

Looks that without X display, tests needs to be run via xvfb, to not show this errors https://github.com/qarmin/czkawka/blob/67db713a059b8b5b066ccf37bf82b7846c3b54ba/.github/workflows/linux.yml#L220

**Comment by fabiscafe** [comment]
Ahh thats it. Thank you. I'll close this issue. :)
